x= {"apple", "banana", "cherry"}
x.add("orange")
print(x)
# x.clear()
# print(x)
# y=x.copy()
# print(y)
y={"google","microsoft","apple"}
# x.difference(y)
# print(y)
# print(x)
# x.difference_update(y)
# print(x)
# x.discard("banana")
# print(x)
# s=x.isdisjoint(y)
# print(s)
# b=x.issubset(y)
# print(x)
# c=x.issuperset(y)
# print(c)
# x.pop()
# print(x)
# print(x)
# x.remove("cherry")
# print(x)
a=x.symmetric_difference(y)
print(y)
print(a)
x.symmetric_difference_update(y)
print(x)
d=x.union(y)
print(d)
x.update(y)
print(x)